[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; upload_protocol = espota
; upload_port = esp32-smarthatch.local
; upload_flags =
;     --auth=SmartHatch2026

lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    tzapu/WiFiManager